title: Quarter Sawn White Oak Dining Table
author: KevinSundstrom
email: kevinsundstrom@github.com
description: > # this means to ignore newlines until "baseurl:"
  A site dedicated to a table. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
